### ISSUE TITLE
Since "Implement Streaming" commit: Handler for textDocument/didOpen failed: TypeError: Cannot read property 'op' of undefined

### ISSUE THREAD

**Issue by danr** [sourcegraph/javascript-typescript-langserver#265]
Hi,

Since 3012e6f0 "Implement Streaming (#217)" I get an error when sending didOpen.
It first sends this partial result:

    {"jsonrpc":"2.0","method":"$/partialResult","params":{"id":0,"patch":[null]}}

And then this error is written:

    ERROR Handler for textDocument/didOpen failed: TypeError: Cannot read property 'op' of undefined
    at compile (/home/dan/build/javascript-typescript-langserver/node_modules/json-patch/jsonpatch.js:509:37)
    at Object.apply (/home/dan/build/javascript-typescript-langserver/node_modules/json-patch/jsonpatch.js:525:14)
    at MapSubscriber.observable.do.map.toArray.map.patches [as project] (/home/dan/build/javascript-typescript-langserver/lib/connection.js:225:46)
    at MapSubscriber._next (/home/dan/build/javascript-typescript-langserver/node_modules/@reactivex/rxjs/dist/cjs/operator/map.js:77:35)
    at MapSubscriber.Subscriber.next (/home/dan/build/javascript-typescript-langserver/node_modules/@reactivex/rxjs/dist/cjs/Subscriber.js:89:18)
    at ToArraySubscriber._complete (/home/dan/build/javascript-typescript-langserver/node_modules/@reactivex/rxjs/dist/cjs/operator/toArray.js:40:26)
    at ToArraySubscriber.Subscriber.complete (/home/dan/build/javascript-typescript-langserver/node_modules/@reactivex/rxjs/dist/cjs/Subscriber.js:114:18)
    at MapSubscriber.Subscriber._complete (/home/dan/build/javascript-typescript-langserver/node_modules/@reactivex/rxjs/dist/cjs/Subscriber.js:132:26)
    at MapSubscriber.Subscriber.complete (/home/dan/build/javascript-typescript-langserver/node_modules/@reactivex/rxjs/dist/cjs/Subscriber.js:114:18)
    at DoSubscriber._complete (/home/dan/build/javascript-typescrip
    
This error does not occur when running its parent commit.

Here is a shell script that triggers the bug:

    tmpdir=$(mktemp -d)
    fifo=$tmpdir/fifo
    mkfifo $fifo
    (while true; do cat $fifo; done) | node lib/language-server-stdio.js &
    pid=$!
    send () {
        cl=$(echo "$1" | wc -c);
        msg="Content-Length: $cl\r\n\r\n$1"
        echo -e "$msg"
        echo -e "$msg" > $fifo
    }
    touch test.ts
    send '{"method":"initialize","params":{"rootUri":"file://'"$PWD"'","capabilities":{}}}'
    sleep 1
    send '{"id":0,"method":"textDocument/didOpen","params":{"textDocument":{"uri":"file://'"$PWD"'/test.ts"},"version":0,"text":""}}'
    sleep 10
    kill -9 $pid
    rm $fifo
    rmdir $tmpdir

The script can be run in the root folder of checking out this repository.

Thanks and thanks for your efforts in making this language server.

**Comment by felixfbecker** [comment]
`textDocument/didOpen` is a notification, but you are calling it like a request. You need to omit the `id` from the message.

http://www.jsonrpc.org/specification#notification

**Comment by danr** [comment]
Oh, I wasn't aware of this distinction, thanks a lot!

**Comment by danr** [comment]
But on a second thought, do you think the error message should be improved? Could it be improved (easily)?

**Comment by felixfbecker** [comment]
Not easily, because the methods are simply mapped to handlers. The handlers don't carry any information on whether they are request or notification handlers. If the message is a request, it starts streaming emitted items by the method, which fails if it is a notification handlers.
