### ISSUE TITLE
Definition of jasmine expect not resolved correctly

### ISSUE THREAD

**Issue by felixfbecker** [sourcegraph/javascript-typescript-langserver#285]
Repro: https://sourcegraph.com/github.com/angular/angular/-/blob/aio/aio-builds-setup/dockerbuild/scripts-js/test/clean-up/build-cleaner.spec.ts#L63:54

**Expected (tsserver):**

![image](https://cloud.githubusercontent.com/assets/10532611/26753428/2cb80b1e-4866-11e7-8f1f-de9c7b49a4a2.png)

**Actual:**

![image](https://cloud.githubusercontent.com/assets/10532611/26753418/00cd6a80-4866-11e7-9f88-c1b4bc8b357c.png)

Which means j2d on `toHaveBeenCalled` fails.

Investigation notes:
- the definition resolved by tsserver is `/aio/aio-builds-setup/dockerbuild/scripts-js/node_modules/@types/jasmine/index.d.ts`

**Comment by felixfbecker** [comment]
@tomv564 maybe you have an idea?

**Comment by tomv564** [comment]
I'd suggest cloning the angular repo and writing an integration-style test for hover.
You can then step through TS's resolution process for build-cleaner.spec with a debugger.

**Comment by felixfbecker** [comment]
Hm, I didn't write a test, but simply ran the LS with a debugger attached. I tried stepping into the TS GoToDefinition code, but that didn't give me any useful insight besides that it stops at some point because some symbol is unknown. The problem is I am stepping through the "reading" code at this point, when the bug is probably at the "writing" code (where the symbol should have been added). I don't know where I would have to set a breakpoint to debug where this symbol should have been added.

**Comment by tomv564** [comment]
There are three projects nested, and each project appears to add definitions to `expect`.

The type returned for `expect` differs depending on what folder I start the service from:
**/aio/aio-builds-setup/dockerbuild/scripts-js/**: 
`function expect(spy: Function): jasmine.Matchers<any> (+2 overloads)`
**/aio**: 
`function expect(spy: Function): jasmine.Matchers<any> (+5 overloads)`
**/**: 
`function expect(spy: Function): jasmine.Matchers<any> (+10 overloads)`
(the text `Create an expectation for a spec.` also disappears at this point)

build-cleaner.spec.ts also has a compilation error:

```
117:29  Argument of type '"Test"' is not assignable to parameter of type 'Expected<void>'.
```

And there is an error loading a reference in `aio`:

```
javascript-typescript-stdio: Error resolving file references for file:///Users/tomv/Projects/angular/angular/aio/aio-builds-setup/dockerbuild/scripts-js/node_modules/%40types/node/index.d.ts: Error: TypeScript config file for /Users/tomv/Projects/angular/angular/aio/node_modules/events/events.js not found
    at ProjectManager.getConfiguration (/Users/tomv/Projects/sourcegraph/javascript-typescript-langserver/lib/project-manager.js:318:19)
    at MergeMapSubscriber.rxjs_1.Observable.from.mergeMap [as project] (/Users/tomv/Projects/sourcegraph/javascript-typescript-langserver/lib/project-manager.js:279:33)
    at MergeMapSubscriber._tryNext (/Users/tomv/Projects/sourcegraph/javascript-typescript-langserver/node_modules/@reactivex/rxjs/dist/cjs/operator/mergeMap.js:120:27)
    at MergeMapSubscriber._next (/Users/tomv/Projects/sourcegraph/javascript-typescript-langserver/node_modules/@reactivex/rxjs/dist/cjs/operator/mergeMap.js:110:18)
    at MergeMapSubscriber.Subscriber.next (/Users/tomv/Projects/sourcegraph/javascript-typescript-langserver/node_modules/@reactivex/rxjs/dist/cjs/Subscriber.js:89:18)
    at /Users/tomv/Projects/sourcegraph/javascript-typescript-langserver/node_modules/@reactivex/rxjs/dist/cjs/observable/PromiseObservable.js:66:36 
```

**Comment by felixfbecker** [comment]
@tomv564 you don't get `function expect(spy: Function): any`? I get that more often than not (even when running the language server with VS Code, not inside Sourcegraph, where it may be a race condition with installing dependencies). Compilation errors shouldn't be the cause since tsserver is able to resolve this correctly...
