### ISSUE TITLE
textDocument/didOpen failing with Cannot read property \'path\' of undefined

### ISSUE THREAD

**Issue by prabirshrestha** [sourcegraph/javascript-typescript-langserver#316]
I can't get the `textDocument/didOpen` to work. `initialize` seems to work fine. I can get `Cannot read property \'path\' of undefined` on Mac and windows. The same code with `go-languageserver` works fine.

Here is the log. Am I missing something?

```log
DEBUG --> { method: 'initialize',
  jsonrpc: '2.0',
  id: 1,
  params: 
   { rootUri: 'file:///Users/prabirshrestha/tmp/helloworld',
     capabilities: {},
     rootPath: 'file:///Users/prabirshrestha/tmp/helloworld' } }
DEBUG <-- { jsonrpc: '2.0',
  method: '$/partialResult',
  params: 
   { id: 1,
     patch: 
      [ { op: 'add',
          path: '',
          value: 
           { capabilities: 
              { textDocumentSync: 1,
                hoverProvider: true,
                signatureHelpProvider: { triggerCharacters: [ '(', ',' ] },
                definitionProvider: true,
                referencesProvider: true,
                documentSymbolProvider: true,
                workspaceSymbolProvider: true,
                xworkspaceReferencesProvider: true,
                xdefinitionProvider: true,
                xdependenciesProvider: true,
                completionProvider: { resolveProvider: false, triggerCharacters: [ '.' ] },
                codeActionProvider: true,
                renameProvider: true,
                executeCommandProvider: { commands: [] },
                xpackagesProvider: true } } } ] } }
DEBUG <-- { jsonrpc: '2.0',
  id: 1,
  result: 
   { capabilities: 
      { textDocumentSync: 1,
        hoverProvider: true,
        signatureHelpProvider: { triggerCharacters: [ '(', ',' ] },
        definitionProvider: true,
        referencesProvider: true,
        documentSymbolProvider: true,
        workspaceSymbolProvider: true,
        xworkspaceReferencesProvider: true,
        xdefinitionProvider: true,
        xdependenciesProvider: true,
        completionProvider: { resolveProvider: false, triggerCharacters: [ '.' ] },
        codeActionProvider: true,
        renameProvider: true,
        executeCommandProvider: { commands: [] },
        xpackagesProvider: true } } }
DEBUG --> { method: 'textDocument/didOpen',
  jsonrpc: '2.0',
  id: 2,
  params: 
   { textDocument: 
      { uri: 'file:///Users/prabirshrestha/tmp/helloworld/hello.ts',
        version: 1,
        languageId: 'typescript',
        text: 'function helloWorld() {\n    console.log(\'hi\')\n}' } } }
DEBUG <-- { jsonrpc: '2.0',
  method: 'textDocument/publishDiagnostics',
  params: 
   { uri: 'file:///Users/prabirshrestha/tmp/helloworld/hello.ts',
     diagnostics: [] } }
DEBUG <-- { jsonrpc: '2.0',
  method: '$/partialResult',
  params: { id: 2, patch: [ undefined ] } }
ERROR Handler for textDocument/didOpen failed: TypeError: Cannot read property 'path' of undefined
    at applyOperation (/Users/prabirshrestha/.nvm/versions/node/v6.9.2/lib/node_modules/javascript-typescript-langserver/node_modules/fast-json-patch/lib/core.js:120:18)
    at ReduceSubscriber.applyReducer [as accumulator] (/Users/prabirshrestha/.nvm/versions/node/v6.9.2/lib/node_modules/javascript-typescript-langserver/node_modules/fast-json-patch/lib/core.js:268:27)
    at ReduceSubscriber._tryReduce (/Users/prabirshrestha/.nvm/versions/node/v6.9.2/lib/node_modules/javascript-typescript-langserver/node_modules/@reactivex/rxjs/dist/cjs/operator/reduce.js:109:27)
    at ReduceSubscriber._next (/Users/prabirshrestha/.nvm/versions/node/v6.9.2/lib/node_modules/javascript-typescript-langserver/node_modules/@reactivex/rxjs/dist/cjs/operator/reduce.js:99:18)
    at ReduceSubscriber.Subscriber.next (/Users/prabirshrestha/.nvm/versions/node/v6.9.2/lib/node_modules/javascript-typescript-langserver/node_modules/@reactivex/rxjs/dist/cjs/Subscriber.js:89:18)
    at DoSubscriber._next (/Users/prabirshrestha/.nvm/versions/node/v6.9.2/lib/node_modules/javascript-typescript-langserver/node_modules/@reactivex/rxjs/dist/cjs/operator/do.js:88:30)
    at DoSubscriber.Subscriber.next (/Users/prabirshrestha/.nvm/versions/node/v6.9.2/lib/node_modules/javascript-typescript-langserver/node_modules/@reactivex/rxjs/dist/cjs/Subscriber.js:89:18)
    at /Users/prabirshrestha/.nvm/versions/node/v6.9.2/lib/node_modules/javascript-typescript-langserver/node_modules/@reactivex/rxjs/dist/cjs/observable/PromiseObservable.js:66:36 
Message: { method: 'textDocument/didOpen',
  jsonrpc: '2.0',
  id: 2,
  params: 
   { textDocument: 
      { uri: 'file:///Users/prabirshrestha/tmp/helloworld/hello.ts',
        version: 1,
        languageId: 'typescript',
        text: 'function helloWorld() {\n    console.log(\'hi\')\n}' } } }
DEBUG <-- { jsonrpc: '2.0',
  id: 2,
  error: 
   { message: 'Cannot read property \'path\' of undefined',
     code: -32001,
     data: {} } }
```

**Comment by felixfbecker** [comment]
`textDocument/didOpen` is a notification, so you need to omit the ID member. Otherwise the LS will treat it as a request and try to send a response, which fails because the handler doesn't return anything. 

> 4.1 Notification
> A Notification is a Request object without an "id" member. A Request object that is a Notification signifies the Client's lack of interest in the corresponding Response object, and as such no Response object needs to be returned to the client. The Server MUST NOT reply to a Notification, including those that are within a batch request.

http://www.jsonrpc.org/specification#notification

**Comment by prabirshrestha** [comment]
Thanks. That fixed the issue.
