### ISSUE TITLE
TYPESCRIPT Server: ERROR Handle textDocumentDidOpen: TypeError: Cannot read property 'ensureReferencedFiles' of undefined

### ISSUE THREAD

**Issue by sriramks85** [sourcegraph/javascript-typescript-langserver#372]
Why am I getting this error:
{ jsonrpc: '2.0',
  id: 0,
  method: 'initialize',
  params: 
   { rootPath: null,
     rootUri: null,
     capabilities: { workspace: [Object], textDocument: [Object] },
     trace: 'off' } }
{ jsonrpc: '2.0',
  id: 0,
  method: 'initialize',
  params: 
   { rootPath: null,
     rootUri: null,
     capabilities: { workspace: [Object], textDocument: [Object] },
     trace: 'off',
     processId: 35444 } }
{ jsonrpc: '2.0',
  method: '$/partialResult',
  params: { id: 0, patch: [ [Object] ] } }
{ jsonrpc: '2.0',
  id: 0,
  result: 
   { capabilities: 
      { textDocumentSync: 1,
        hoverProvider: true,
        signatureHelpProvider: [Object],
        definitionProvider: true,
        referencesProvider: true,
        documentSymbolProvider: true,
        workspaceSymbolProvider: true,
        xworkspaceReferencesProvider: true,
        xdefinitionProvider: true,
        xdependenciesProvider: true,
        completionProvider: [Object],
        codeActionProvider: true,
        renameProvider: true,
        executeCommandProvider: [Object],
        xpackagesProvider: true } } }
{ jsonrpc: '2.0', method: 'initialized', params: {} }
{ jsonrpc: '2.0',
  method: 'textDocument/didOpen',
  params: 
   { textDocument: 
      { uri: 'file:///Users/mettl358/Documents/mettl/workspace/script.ts',
        languageId: 'ts',
        version: 1,
        text: '{\n    "$schema": "http://json.schemastore.org/coffeelint",\n    "line_endings": "unix"\n}' } } }
TYPESCRIPT Server: WARN  Method initialized not implemented

{ jsonrpc: '2.0',
  id: 1,
  method: 'textDocument/codeAction',
  params: 
   { textDocument: { uri: 'file:///Users/mettl358/Documents/mettl/workspace/script.ts' },
     range: { start: [Object], end: [Object] },
     context: { diagnostics: [] } } }
{ jsonrpc: '2.0',
  id: 1,
  method: 'textDocument/codeAction',
  params: 
   { textDocument: { uri: 'file:///Users/mettl358/Documents/mettl/workspace/script.ts' },
     range: { start: [Object], end: [Object] },
     context: { diagnostics: [] } } }
TYPESCRIPT Server: ERROR Handle textDocumentDidOpen: TypeError: Cannot read property 'ensureReferencedFiles' of undefined
    at TypeScriptService.<anonymous> (/Users/mettl358/Documents/mettl/javascript-typescript-langserver/lib/typescript-service.js:1048:38)
    at next (native)
    at /Users/mettl358/Documents/mettl/javascript-typescript-langserver/lib/typescript-service.js:7:71
    at __awaiter (/Users/mettl358/Documents/mettl/javascript-typescript-langserver/lib/typescript-service.js:3:12)
    at TypeScriptService.textDocumentDidOpen (/Users/mettl358/Documents/mettl/javascript-typescript-langserver/lib/typescript-service.js:1045:16)
    at Object.<anonymous> (/Users/mettl358/Documents/mettl/javascript-typescript-langserver/lib/connection.js:200:48)
    at next (native)
    at /Users/mettl358/Documents/mettl/javascript-typescript-langserver/lib/connection.js:7:71
    at __awaiter (/Users/mettl358/Documents/mettl/javascript-typescript-langserver/lib/connection.js:3:12)
    at MessageEmitter.messageEmitter.on (/Users/mettl358/Documents/mettl/javascript-typescript-langserver/lib/connection.js:124:47)

TYPESCRIPT Server: ERROR Handler for textDocument/codeAction failed: TypeError: Cannot read property 'ensureReferencedFiles' of undefined
    at TypeScriptService.textDocumentCodeAction (/Users/mettl358/Documents/mettl/javascript-typescript-langserver/lib/typescript-service.js:909:35)
    at Object.<anonymous> (/Users/mettl358/Documents/mettl/javascript-typescript-langserver/lib/connection.js:200:48)
    at next (native)
    at /Users/mettl358/Documents/mettl/javascript-typescript-langserver/lib/connection.js:7:71
    at __awaiter (/Users/mettl358/Documents/mettl/javascript-typescript-langserver/lib/connection.js:3:12)
    at MessageEmitter.messageEmitter.on (/Users/mettl358/Documents/mettl/javascript-typescript-langserver/lib/connection.js:124:47)
    at emitOne (events.js:101:20)
    at MessageEmitter.emit (events.js:188:7)
    at StreamMessageReader.MessageEmitter.reader.listen.msg [as callback] (/Users/mettl358/Documents/mettl/javascript-typescript-langserver/lib/connection.js:48:18)
    at StreamMessageReader.onData (/Users/mettl358/Documents/mettl/javascript-typescript-langserver/node_modules/vscode-jsonrpc/lib/messageReader.js:220:18) 
Message: { jsonrpc: '2.0',
  id: 1,
  method: 'textDocument/codeAction',
  params: 
   { textDocument: { uri: 'file:///Users/mettl358/Documents/mettl/workspace/script.ts' },
     range: 
      { start: { line: 0, character: 0 },
        end: { line: 0, character: 0 } },
     context: { diagnostics: [] } } }

{ jsonrpc: '2.0',
  id: 1,
  error: 
   { message: 'Cannot read property \'ensureReferencedFiles\' of undefined',
     code: -32001,
     data: {} } }

**Comment by felixfbecker** [comment]
You did not send a `rootUri`. Is that intentional? What client is this?

**Comment by sriramks85** [comment]
I am using monaco editor with this client 
https://github.com/TypeFox/monaco-languageclient.
I can provide monaco.Uri in (client.ts), is this what you are talking about?

**Comment by felixfbecker** [comment]
I am not familiar with that editor. This language server doesn't currently work without a `rootUri`.

**Comment by rcjsuen** [comment]
The specification states that both `rootPath` and `rootUri` can be `null`. However, if this language server won't run without a `rootPath` or `rootUri` then that's life. Perhaps it should throw an error back to the client?

Not sure which is more appropriate between `InvalidParams` or `InvalidRequest` though. I'm guessing `InvalidParams`?
