### ISSUE TITLE
Client capabilities not respected

### ISSUE THREAD

**Issue by Naatan** [sourcegraph/javascript-typescript-langserver#386]
I'm passing xcontentProvider and xfilesProvider both as `false`, but the server is still trying to use workspace/xfiles to resolve files.

Reproducible with this sample code:

```js
var cp = require("child_process");
var rpc = require("vscode-jsonrpc");

var binary = "/usr/lib/node_modules/javascript-typescript-langserver/lib/language-server-stdio.js";
var args = ["--trace", "--strict", "--logfile", "/tmp/lsp.log"];

let childProcess = cp.spawn(binary,args);

childProcess.stderr.on("data", (d) => console.log(d));
childProcess.on("error", console.error);
childProcess.on("close", console.warn);

// Use stdin and stdout for communication:
let connection = rpc.createMessageConnection(
    new rpc.StreamMessageReader(childProcess.stdout),
    new rpc.StreamMessageWriter(childProcess.stdin),
    {
        error: console.error
    }
);

let notification = new rpc.NotificationType('testNotification');

connection.listen();

var ready = () =>
{

    connection.sendRequest("textDocument/completion", {
        textDocument: { uri: "file:///tmp/foo.ts" },
        position: 1
    }).then(console.log).catch(console.error);
};

connection.sendRequest("initialize", {
    processId: process.pid,
    rootPath: "/tmp",
    rootUri: "file:///tmp",
    initializationOptions: {},
    capabilities: {
        xcontentProvider: false,
        xfilesProvider: false,
    },
    trace: "verbose"
}).then(ready).catch(console.error);

setTimeout(() => childProcess.stdin.destroy(), 1000);
```

Result:

```
{ Error: Unhandled method workspace/xfiles
    at new ResponseError (/home/nathan/Projects/lsp-server-test/node_modules/vscode-jsonrpc/lib/messages.js:46:28)
    at handleResponse (/home/nathan/Projects/lsp-server-test/node_modules/vscode-jsonrpc/lib/main.js:423:48)
    at processMessageQueue (/home/nathan/Projects/lsp-server-test/node_modules/vscode-jsonrpc/lib/main.js:251:17)
    at Immediate._onImmediate (/home/nathan/Projects/lsp-server-test/node_modules/vscode-jsonrpc/lib/main.js:235:13)
    at runCallback (timers.js:785:20)
    at tryOnImmediate (timers.js:747:5)
    at processImmediate [as _immediateCallback] (timers.js:718:5) code: -32601, data: {} }
```

Note I believe these should be passed via `ClientCapabilities.experimental`, as per the protocol. But from reading the source they seem to be passed directly under `ClientCapabilities`. I tried changing the defaults to `false` in the server source, but the problem persisted. Suggesting that the capabilities aren't being properly considered.

**Comment by felixfbecker** [comment]
You are passing `--strict`, which forces the server to _never_ read from disk, no matter what capabilities the client sends.

**Comment by Naatan** [comment]
Thanks @felixfbecker, that was indeed the issue.
