### ISSUE TITLE
Filenames with `%` breaks server

### ISSUE THREAD

**Issue by autozimu** [sourcegraph/javascript-typescript-langserver#422]
For a simplified situation, in a folder named sample-js, with two files,
- `test.js`
- `%test.js`

The server will quit with this error
```
/usr/local/lib/node_modules/javascript-typescript-langserver/lib/util.js:46
    const pathParts = parts.pathname.split('/').map(segment => encodeURIComponent(decodeURIComponent(segment)));
                                                                                  ^

URIError: URI malformed
    at decodeURIComponent (<anonymous>)
    at parts.pathname.split.map.segment (/usr/local/lib/node_modules/javascript-typescript-langserver/lib/util.js:46:83)
    at Array.map (<anonymous>)
    at Object.normalizeUri (/usr/local/lib/node_modules/javascript-typescript-langserver/lib/util.js:46:49)
    at Glob.globber.on (/usr/local/lib/node_modules/javascript-typescript-langserver/lib/fs.js:62:40)
    at Glob.emit (events.js:159:13)
    at Glob._emitMatch (/usr/local/lib/node_modules/javascript-typescript-langserver/node_modules/glob/glob.js:489:8)
    at Glob._processSimple2 (/usr/local/lib/node_modules/javascript-typescript-langserver/node_modules/glob/glob.js:705:8)
    at /usr/local/lib/node_modules/javascript-typescript-langserver/node_modules/glob/glob.js:676:10
    at Glob._stat2 (/usr/local/lib/node_modules/javascript-typescript-langserver/node_modules/glob/glob.js:789:10)
```

File names like `%` are used by vim as backup files and are not rare to encounter.

**Comment by autozimu** [comment]
Affects https://github.com/autozimu/LanguageClient-neovim/issues/259

**Comment by felixfbecker** [comment]
Could you post the LSP logs? I would like to see what URIs neovim sends.

**Comment by autozimu** [comment]
https://pastebin.com/E7G94M3h

The LSP messages are nothing suspicious.

It looks like the error is happening when language server tried to index the whole folder.

**Comment by GCorbel** [comment]
I have a similar issue. It fails when it try to get the file `tmp/bundle/gems/railties-4.2.7.1/lib/rails/generators/rails/generator/templates/%file_name%_generator.rb.tt`. I tried to do a exception handler and it works.
