### ISSUE TITLE
Bad File Name Make server collapse

### ISSUE THREAD

**Issue by kongds** [sourcegraph/javascript-typescript-langserver#476]
If the server scan path like this 'file:///Users/royokong/Desktop/net/%S_(2NV~X3K3_GY%}R~MO)Q.png' the server will collapse, because it's a illegal URL. 
the Error is occured in src/util.ts:47 at normalizeUri.

**Comment by felixfbecker** [comment]
What do you mean with "collapse"? Where does the URL come from?

**Comment by kongds** [comment]
For example, when scanning the file like %S_(2NV~X3K3_GY%}R~MO)Q.png  in my root path
URIError: URI malformed
    at decodeURIComponent (<anonymous>)
    at parts.pathname.split.map.segment (/Users/royokong/Desktop/javascript-typescript-langserver/lib/util.js:46:83)
    at Array.map (<anonymous>)
    at Object.normalizeUri (/Users/royokong/Desktop/javascript-typescript-langserver/lib/util.js:46:49)
    at Glob.globber.on (/Users/royokong/Desktop/javascript-typescript-langserver/lib/fs.js:62:40)
    at Glob.emit (events.js:182:13)
    at Glob._emitMatch (/Users/royokong/Desktop/javascript-typescript-langserver/node_modules/glob/glob.js:489:8)
    at Glob._processSimple2 (/Users/royokong/Desktop/javascript-typescript-langserver/node_modules/glob/glob.js:705:8)
    at /Users/royokong/Desktop/javascript-typescript-langserver/node_modules/glob/glob.js:676:10
    at Glob._stat2 (/Users/royokong/Desktop/javascript-typescript-langserver/node_modules/glob/glob.js:789:10)
