### ISSUE TITLE
Error resolving file references

### ISSUE THREAD

**Issue by romgrk** [sourcegraph/javascript-typescript-langserver#559]
Hey,

I've recently started seing these errors pop up, I'm not sure what I should do to fix them. Any idea?

```
[LC] [Error] Error resolving file references for file:///home/rgregoir/projects/triton/helpers/clarity-database.js:
    Error: TypeScript config file for /home/rgregoir/projects/triton/node_modules/chalk/types/index.d.ts not found
    at ProjectManager.getConfiguration (/home/rgregoir/.cache/npm-global/lib/node_modules/javascript-typescript-langserver/lib/project-manager.js:675:19)
    at DeferSubscriber.observable.updater.ensure.concat.rxjs_1.Observable.defer [as factory] (/home/rgregoir/.cache/npm-global/lib/node_modules/javascript-typescript-langserver/lib/project-manager.js:635:33)
    at DeferSubscriber._callFactory (/home/rgregoir/.cache/npm-global/lib/node_modules/javascript-typescript-langserver/node_modules/rxjs/observable/DeferObservable.js:92:27)
    at DeferSubscriber.tryDefer (/home/rgregoir/.cache/npm-global/lib/node_modules/javascript-typescript-langserver/node_modules/rxjs/observable/DeferObservable.js:85:18)
    at new DeferSubscriber (/home/rgregoir/.cache/npm-global/lib/node_modules/javascript-typescript-langserver/node_modules/rxjs/observable/DeferObservable.js:81:14)
    at DeferObservable._subscribe (/home/rgregoir/.cache/npm-global/lib/node_modules/javascript-typescript-langserver/node_modules/rxjs/observable/DeferObservable.js:71:16)
    at DeferObservable.Observable._trySubscribe (/home/rgregoir/.cache/npm-global/lib/node_modules/javascript-typescript-langserver/node_modules/rxjs/Observable.js:172:25)
    at DeferObservable.Observable.subscribe (/home/rgregoir/.cache/npm-global/lib/node_modules/javascript-typescript-langserver/node_modules/rxjs/Observable.js:160:93)
    at Object.subscribeToResult (/home/rgregoir/.cache/npm-global/lib/node_modules/javascript-typescript-langserver/node_modules/rxjs/util/subscribeToResult.js:23:27)
    at MergeMapSubscriber._innerSub (/home/rgregoir/.cache/npm-global/lib/node_modules/javascript-typescript-langserver/node_modules/rxjs/operators/mergeMap.js:132:38)
```

**Comment by garyo** [comment]
Anything? I'm seeing these too.
